### ISSUE TITLE
Large files

### ISSUE THREAD

**Issue by AidinHamedi** [michalmonday/CSV-Parser-for-Arduino#20]
in large files cant work

**Comment by michalmonday** [comment]
It is limited by memory of specific microcontroller. Which is shown on page 10 of [Memories of an Arduino](https://cdn-learn.adafruit.com/downloads/pdf/memories-of-an-arduino.pdf) (SRAM column)

![image](https://user-images.githubusercontent.com/16074078/212538099-f83a608b-0dbc-4e1f-aa9c-0538a403edeb.png)
